Input redesign
SurajPratap10/Imagine_AI pull request #414
Opened 2023-06-23 12:42 UTC by AlfiyaSiddique

Hello @SurajPratap10 

# Description
Changed the input design of forms

## Fixes #372  **change in Inputs of Login and signup**

## Screenshots
The design is as follows:

## Signup
<img width="951" alt="1" src="https://github.com/SurajPratap10/Imagine_AI/assets/86224794/526051a3-b23b-4f1a-b500-194aaad7fed3">

## Login
<img width="960" alt="2" src="https://github.com/SurajPratap10/Imagine_AI/assets/86224794/aa247af6-3bc0-4cb0-9db6-8210a6070199">

How's It?

I think we should change the button as well so it matches with the rest of the input. If you allow I will change the button so that it matches with the rest of the inputs and I will implement related animation too in the button.

Please share your feedback.

## Checklist

- [x] Tests have been added or updated to cover the changes
- [ ] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

2023-06-25 12:23 UTC, SurajPratap10 requested changes
Resolve the `conflicts`

2023-06-25 13:15 UTC, AlfiyaSiddique commented
Heyc@SurajPratap10  Conflicts Resolved. 👍🏻

2023-06-26 15:55 UTC, SurajPratap10 requested changes
![image](https://github.com/SurajPratap10/Imagine_AI/assets/92919173/48df0f87-b4fb-4961-9096-c0e4e2f89015)

- `Enter` correct it
- Give some `border-radius` same as the submit,generate buttons

2023-06-26 16:09 UTC, SurajPratap10 approved these changes

2023-06-26 16:09 UTC, merged