Added responsive for login and signup pages
SurajPratap10/Imagine_AI pull request #472
Opened 2023-06-26 19:15 UTC by saikiranreddy201

# Description

The login and signup pages are overlapping the header and footer in my screen which is 1200px. I have fixed the issue

## Fixes #411 

## Screenshots
![image](https://github.com/SurajPratap10/Imagine_AI/assets/98690105/ac1daf87-dce7-48a0-bd5c-36176fcfcb86)
![image](https://github.com/SurajPratap10/Imagine_AI/assets/98690105/7e690223-e481-4841-ada2-255b29d6e35a)

## Checklist

- [x] Tests have been added or updated to cover the changes
- [x] Documentation has been updated to reflect the changes
- [x] Code follows the established coding style guidelines
- [x] All tests are passing

2023-06-27 15:44 UTC, SurajPratap10 requested changes
Resolve the `conflicts` @saikiranreddy201

2023-06-27 17:51 UTC, saikiranreddy201 commented
Hey @SurajPratap10, I have resolved the conflicts. please review!

2023-06-28 15:30 UTC, SurajPratap10 approved these changes

2023-06-28 15:30 UTC, merged

2023-06-28 15:36 UTC, saikiranreddy201 commented
Hey @SurajPratap10  please add a level label for my other pr #453, so that my pr counts in the total score